name: docushot
description: A local-first document scanning application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.2.1

  # Local Database
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3

  # ML Kit
  google_mlkit_document_scanner: ^0.4.0
  google_mlkit_text_recognition: ^0.15.0

  # Permissions
  permission_handler: ^11.4.0

  # In-App Purchase
  in_app_purchase: ^3.2.0

  # Utilities
  pdf: ^3.10.0
  share_plus: ^12.0.1
  archive: ^4.0.9
  path_provider: ^2.1.2
  uuid: ^4.3.3
  intl: ^0.20.2

  # UI
  reorderable_grid_view: ^2.2.5
  cupertino_icons: ^1.0.6
  image_picker: ^1.2.1
  image: ^4.1.7 # For pixel-level manipulation (filters)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
